Repository FU-Hagen-Discord/fernuni-bot, pull requests merged in 2024-04, with the labels that each got.

#228 Umformulierungen ftw
  extensions/appointments.py
  extensions/module_information.py
Labels: enhancement, user experience

#229 Grundlegende Änderung des Begrüßungstexts bei LG-Erstellung
  cogs/learninggroups.py
Labels: enhancement, Lerngruppen, user experience

#206 Release v1.1.4
  cogs/learninggroups.py
  images/Boty_Herbst_mit_Blaettern_und_Laecheln.png
  images/Botys_Profilbild.xcf
  images/Botys_Profilbild_Halloween.png
  images/Botys_Profilbild_Sommer.png
  images/Ghosty_Profilbild.png
  images/MI_Banner_wiese_16x9_nur_boty.gif
  images/elfy profilbild.png
Labels: Release
